In [2]:
import numpy as np

In [3]:
escalar = np.array(42)

print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [4]:
vector = np.array([30,29, 35, 31, 33, 36, 42])

print(vector)

[30 29 35 31 33 36 42]


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
tensor = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])

print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [7]:
array_arange = np.arange(10)

print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
eye_matrix = np.eye(6)

print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [9]:
diag = np.diag([1, 2, 3, 4, 5, 6])

print(diag)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [10]:
random = np.random.random((2, 3))

print(random)

[[0.77499616 0.90402036 0.99027003]
 [0.52812879 0.05010494 0.40932896]]
