In [2]:
import numpy as np

In [3]:
array = np.array([10, 20, 30, 40, 50])
print(array[1])
print(array[-1])

20
50


In [4]:
print(array[1:4])

[20 30 40]


In [5]:
print(array[1:10])

[20 30 40 50]


In [7]:
print(array[-1:-7])

[]


In [9]:
bool_index = array > 25

print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [11]:
index = [2, 0, 4]
print(array[index])

[30 10 50]


In [26]:
array = np.random.randint(1, 10, size=(3,3))

print(array)
print(array[0,1])

[[7 9 5]
 [9 9 9]
 [4 1 4]]
9


In [27]:
print(array[:2,:2])

[[7 9]
 [9 9]]
