In [1]:
import numpy as np

In [2]:
prices = np.array([100, 200, 300])
discount = np.array([0.9])

discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [3]:
prices = np.random.randint(100, 500, size=(3, 3))
print(prices)

discount = np.array([10, 20, 30])

discount_prices = prices - discount
print(discount_prices)

[[473 313 365]
 [213 109 127]
 [348 149 433]]
[[463 293 335]
 [203  89  97]
 [338 129 403]]


all: es para comprobar todos

In [4]:
array = np.array([1, 2, 3, 4, 5])

print(np.all(array > 0))
print(np.all(array > 3))

True
False


any: es para comprobar si alguno

In [5]:
print(np.any(array > 4))

True


In [6]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

concatenated_aa = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))

print(concatenated_aa)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


In [7]:
stacked_v = np.vstack((array_a, array_b))

print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [8]:
satacked_h = np.hstack((array_a, array_b))

print(satacked_h)

[1 2 3 4 5 6]


In [9]:
array_c = np.arange(1, 10)
# la longitud del array debe ser divisible entre el numero de saltos
split_array = np.split(array_c, 3)

print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
