In [1]:
import numpy as np

In [2]:
surwey_responses = np.array([
    "bueno", "excelente", "malo", 
    "bueno", "malo", "excelente", 
    "bueno", "bueno", "malo", "excelente"
])

print(np.unique(surwey_responses))

['bueno' 'excelente' 'malo']


In [3]:
unique_elements, count = np.unique(surwey_responses, return_counts=True)

print(unique_elements)
print(count)

['bueno' 'excelente' 'malo']
[4 3 3]


# vistas

In [4]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]


In [5]:
array_x[1:3] = [10, 11]

print(array_x)
print(view_y)

[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [6]:
array_y = np.arange(10)
copy_y = array_y[[1,2]]

print(array_y)
print(copy_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]


In [7]:
array_y[1:3] = [10, 11]

print(array_y)
print(copy_y)

[ 0 10 11  3  4  5  6  7  8  9]
[1 2]
