In [7]:
import numpy as np

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)
print(A - B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


# multilpicacion

In [9]:
print(A.dot(B))
print(B.dot(A))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


# determinante

In [11]:
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

print(det_A)
print(inv_A)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


## resolver AX = B

In [12]:
b = np.array([9, 11])
x = np.linalg.solve(A, b)

print(x)

[-7.  8.]
